version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
  
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/Users/edwin.cabezas/Documents/personales/repositories/concept-expressjs-middleware/sessions/data/db

volumes:
  mongodb_data_container: